### ISSUE TITLE
Warning: in_array() expects parameter 2 to be array

### ISSUE THREAD

**Issue by colin-walker** [pfefferle/wordpress-semantic-linkbacks#196]
With WP_DEBUG set to true I get the following when listing comments:

Warning: in_array() expects parameter 2 to be array, string given in {path to}/class-linkbacks-walker-comment.php on line 25

**Comment by colin-walker** [comment]
This error (and a similar error in semantic-linkbacks.php line 97) occurs when all facepile options are deselected.

I’ve worked around it by checking if $facepiles is a string and if so setting $facepiles[0] = $facepiles

Doesn’t do anything and the error doesn’t cause any impact (it’s only visible with wp_debug =true) but at least the error goes away ;)

**Comment by pfefferle** [comment]
Should be fixed with #192 

Will rollout an update later today.

**Comment by colin-walker** [comment]
Thanks.

**Comment by edent** [comment]
This still seems to be a problem. My logfiles are full of:

```

PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 2
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 16
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 30
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 44
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 58
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 72
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 86
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 100
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 114
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 128
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 144
PHP Warning:  in_array() expects parameter 2 to be array, string given in blog/wp-content/plugins/semantic-linkbacks/templates/linkbacks.php on line 210
```

**Comment by colin-walker** [comment]
Have you unticled all of the facepiles options? I still don't think it's handling that correctly.

**Comment by edent** [comment]
I don't have facepiles enabled at all. And the "Initial number" is set to 0.
